//! Defines the `Signature` struct.

use crate::{field::Elem, poly::Polynomial};

/// The signature generated by the signing algorithm which takes
/// setup with prime modulus P.
#[derive(Clone, Debug)]
pub struct Signature<const P: u32> {
    pub(crate) z1: Polynomial<Elem<P>>,
    pub(crate) z2: Polynomial<Elem<P>>,
    pub(crate) c: Polynomial<Elem<P>>,
}
