//! Defines the `Signature` struct.

use crate::field::Elem;
use poly_ring_xnp1::Polynomial;

/// The signature generated by the signing algorithm which takes
/// setup with prime modulus P.
#[derive(Clone, Debug)]
pub struct Signature<const P: u32, const N: usize> {
    pub(crate) z1: Polynomial<Elem<P>, N>,
    pub(crate) z2: Polynomial<Elem<P>, N>,
    pub(crate) c: Polynomial<Elem<P>, N>,
}
